-- MySQL Script generated by MySQL Workbench
-- Sun Jul  3 20:37:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema guarderiaMascotas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema guarderiaMascotas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `guarderiaMascotas` DEFAULT CHARACTER SET latin1 ;
USE `guarderiaMascotas` ;

-- -----------------------------------------------------
-- Table `guarderiaMascotas`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guarderiaMascotas`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `guarderiaMascotas`.`daycares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guarderiaMascotas`.`daycares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `price` INT NOT NULL,
  `category_id` INT NOT NULL,
  `characteristics` VARCHAR(200) NOT NULL,
  `facilities` VARCHAR(200) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_32b7ff9d-4ef4-4ef1-b7ad-3ab7a1210aa0` (`category_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `guarderiaMascotas`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guarderiaMascotas`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `adress` VARCHAR(100) NULL DEFAULT NULL,
  `dni` INT NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `guarderiaMascotas`.`usersDaycares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guarderiaMascotas`.`usersDaycares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `daycares_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_cb0c16f7-6881-4a03-9fe6-54a45640da14` (`users_id` ASC) VISIBLE,
  INDEX `FK_6e43db3b-418e-4629-97ae-00359f750c6b` (`daycares_id` ASC) VISIBLE,
  CONSTRAINT `FK_6e43db3b-418e-4629-97ae-00359f750c6b`
    FOREIGN KEY (`daycares_id`)
    REFERENCES `guarderiaMascotas`.`daycares` (`id`),
  CONSTRAINT `FK_cb0c16f7-6881-4a03-9fe6-54a45640da14`
    FOREIGN KEY (`users_id`)
    REFERENCES `guarderiaMascotas`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
